### ISSUE TITLE
Issues with AUX AC swing modes

### ISSUE THREAD

**Issue by infernix** [ArtemVladimirov/broadlinkac2mqtt#19]
Hi, 

I recently switched from liaan/broadlink_ac_mqtt to this, and am having some issues with an AUX AC.

One is that the swing mode sometimes seems to get stuck on a loop, and it keeps submitting a state which makes the AC beep until I restart. It looks as if this happens if fan mode is in `auto` and i set swing mode to anything other than `auto`. Here's the log for that:

```
Jul 23 02:52:21 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","status":{"FanMode":"mute","SwingMode":"top","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T02:52:21+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
Jul 23 02:52:23 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","device":"c8f74291b0a6","payload":"auto","topic":"/aircon/c8f74291b0a6/fan_mode/set","time":"2023-07-23T02:52:23+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/mqtt/subscriber/subscriber.go:31","message":"new update fan mode message"}
Jul 23 02:52:24 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","status":{"FanMode":"mute","SwingMode":"top","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T02:52:24+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
Jul 23 02:52:25 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","status":{"FanMode":"auto","SwingMode":"top","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T02:52:25+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
```
I then set fanmode to bottom, and then this just loops forever, beeping once per ~1-2 seconds, until I restart broadlinkac2mqtt:
```
Jul 23 02:52:30 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","device":"c8f74291b0a6","payload":"bottom","topic":"/aircon/c8f74291b0a6/swing_mode/set","time":"2023-07-23T02:52:30+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/mqtt/subscriber/subscriber.go:50","message":"new update swing mode message"}
Jul 23 02:52:31 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","status":{"FanMode":"auto","SwingMode":"top","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T02:52:31+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
Jul 23 02:52:32 raspberrypi broadlinkac2mqtt[8980]: {"level":"debug","status":{"FanMode":"auto","SwingMode":"bottom","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T02:52:32+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
...
```

The other problem is a SEGFAULT which also happens when changing the swing mode. Seems to happen if fan mode is on mute and i set swing mode to anything other than what it is set to. Here's the output:

```
Jul 23 02:49:33 raspberrypi broadlinkac2mqtt[8813]: {"level":"debug","ambientTemp":26,"device":"c8f74291b0a6","time":"2023-07-23T02:49:33+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:293","message":"Ambient temperature"}
Jul 23 02:49:34 raspberrypi broadlinkac2mqtt[8813]: {"level":"debug","status":{"FanMode":"mute","SwingMode":"top","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T02:49:34+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: {"level":"debug","device":"c8f74291b0a6","payload":"auto","topic":"/aircon/c8f74291b0a6/swing_mode/set","time":"2023-07-23T02:49:38+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/mqtt/subscriber/subscriber.go:50","message":"new update swing mode message"}
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x305c38]
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: goroutine 34 [running]:
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: github.com/ArtemVladimirov/broadlinkac2mqtt/app/service.(*service).StartDeviceMonitoring(0x1494480, {0x3e56c0, 0x1494300}, 0x1494330, 0x1410210)
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]:         /home/gerben/src/broadlinkac2mqtt/app/service/service.go:1116 +0x70c
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: main.(*App).Run.func1()
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]:         /home/gerben/src/broadlinkac2mqtt/main.go:171 +0x310
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]: created by main.(*App).Run
Jul 23 02:49:38 raspberrypi broadlinkac2mqtt[8813]:         /home/gerben/src/broadlinkac2mqtt/main.go:150 +0x478
```

This is running 1c4e744930d78da1b72a1f374ca677a453f14d8a and it was the same before the refactor, so doesn't look like a recently introduced issue.

Let me know if you need more debug data.

**Comment by ArtemVladimirov** [comment]
Thanks! I fixed the error, the wrong value was saved.

**Comment by ArtemVladimirov** [comment]
Please, check the fix with this [beta release](https://github.com/ArtemVladimirov/broadlinkac2mqtt/releases/tag/v1.4.0-beta) or using the dev branch of [hassio addon ](https://github.com/ArtemVladimirov/hassio-add-ons).

**Comment by infernix** [comment]
Fixed. There's some additional weirdness, if it's in `mute` mode and i try to set swing mode to `swing`, this happens:

```
Jul 23 22:54:25 raspberrypi broadlinkac2mqtt[28041]: {"level":"debug","device":"c8f74291b0a6","payload":"swing","topic":"/aircon/c8f74291b0a6/swing_mode/set","time":"2023-07-23T22:54:25+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/mqtt/subscriber/subscriber.go:50","message":"new update swing mode message"}
Jul 23 22:54:26 raspberrypi broadlinkac2mqtt[28041]: {"level":"debug","status":{"FanMode":"mute","SwingMode":"auto","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T22:54:26+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
Jul 23 22:54:27 raspberrypi broadlinkac2mqtt[28041]: {"level":"debug","status":{"FanMode":"mute","SwingMode":"","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T22:54:27+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
Jul 23 22:54:27 raspberrypi home-assistant/38264391d62a[667]: 2023-07-23 22:54:27.800 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid swing_modes mode: 
Jul 23 22:54:39 raspberrypi broadlinkac2mqtt[28041]: {"level":"debug","status":{"FanMode":"mute","SwingMode":"","Mode":"cool","Temperature":25},"device":"c8f74291b0a6","time":"2023-07-23T22:54:39+04:00","caller":"/home/gerben/src/broadlinkac2mqtt/app/service/service.go:460","message":"The converted current device status"}
```

Note how SwingMode is `""`. 

But, no segfaults, and no repeated beeping due to status messages.

**Comment by ArtemVladimirov** [comment]
I opened the new issue and will close this
